CRUD/urls.py
from django.urls import path
from CRUD import views


app_name = "CRUD"


urlpatterns = [

    path('', views.index, name='index'),
    path('add_musician/', views.musician_form, name='musician_form'),
    path('add_album/', views.album_form, name='album_form'),
    path('album_list/<int:musician_id>/', views.album_list, name='album_list'),
    path('update_musician/<int:musician_id>/', views.update_musician, name='update_musician'),
    path('update_album/<int:album_id>/', views.update_album, name='update_album'),
    path('delete_album/<int:album_id>/', views.delete_album, name='delete_album'),
    path('delete_musician/<int:musician_id>/', views.delete_musician, name='delete_musician'),
]

CRUD_Operation_with_Django/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CRUD.urls')),
]

CRUD/models.py
from django.db import models

# Create your models here.
class Musician(models.Model):
    # id = models.AutoField(Primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)

    # class Meta:
        # db_table = "musician"

    def __str__(self):
        return self.first_name + " " + self.last_name

class Album(models.Model):
    # id = models.AutoField(Primary_key=True)
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField()
    rating = (
    (1, "Worst"),
    (2, "Bad"),
    (3, "Not Bad"),
    (4, "Good"),
    (5, "Excellent!"),
    )
    num_stars = models.IntegerField(choices=rating)


    def __str__(self):
        return self.name + ", Rating: " + str(self.num_stars)

CRUD/forms.py
from django import forms
from CRUD import models

class MusicianForm(forms.ModelForm):
    class Meta:
        model = models.Musician
        fields = "__all__"

class AlbumForm(forms.ModelForm):
    release_date = forms.DateField( widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = models.Album
        fields = "__all__"

CRUD/views.py
from django.shortcuts import render
from django.http import HttpResponse
from CRUD.models import Musician, Album
from CRUD import forms
from django.db.models import Avg

# Create your views here.
def index(request):
    musician_list = Musician.objects.order_by("first_name")

    diction = {'title':'Home Page', 'musician_list':musician_list}
    return render(request,'CRUD/index.html',context=diction)

def album_list(request, musician_id):
    musician_info = Musician.objects.get(pk=musician_id)
    album_list = Album.objects.filter(artist=musician_id).order_by('name','release_date')
    musician_rating_avg = Album.objects.filter(artist=musician_id).aggregate(Avg('num_stars'))

    diction = {'title':'List of Albums', 'musician_info':musician_info, 'album_list':album_list, 'musician_rating_avg':musician_rating_avg}
    return render(request,'CRUD/album_list.html',context=diction)

def musician_form(request):
    form = forms.MusicianForm()

    if request.method == 'POST':
        form = forms.MusicianForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
    diction = {'title':'Add New Musician', 'musician_form':form}
    return render(request,'CRUD/musician_form.html',context=diction)

def album_form(request):
    form = forms.AlbumForm()

    if request.method == 'POST':
        form = forms.AlbumForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'title':'Add New Album', 'album_form':form}
    return render(request,'CRUD/album_form.html',context=diction)

def update_musician(request, musician_id):
    musician_info = Musician.objects.get(pk=musician_id)
    form = forms.MusicianForm(instance=musician_info)

    if request.method == 'POST':
        form = forms.MusicianForm(request.POST, instance=musician_info)

        if form.is_valid():
            form.save(commit=True)
            return album_list(request, musician_id)


    diction = {'update_form':form}
    return render(request, 'CRUD/update_musician.html', context=diction)


def update_album(request, album_id):
    album_info = Album.objects.get(pk=album_id)
    form = forms.AlbumForm(instance=album_info)
    diction = {}
    if request.method == 'POST':
        form = forms.AlbumForm(request.POST, instance=album_info)

        if form.is_valid():
            form.save(commit=True)
            diction.update({'success_text':'Successfully Updated!'})

    diction.update({'update_form':form})
    return render(request,'CRUD/update_album.html', context=diction)

def delete_album(request, album_id):
    album = Album.objects.get(pk=album_id).delete()
    diction = {'delete_success':'Album Deleted Successfully!'}
    return render(request, 'CRUD/delete.html', context=diction)

def delete_musician(request, musician_id):
    artist = Musician.objects.get(pk=musician_id).delete(0)
    diction = {'delete_success':'Musician Deleted Successfully!'}
    return render(request, 'CRUD/delete.html', context=diction)

templates/CRUD/album_form.html
<!DOCTYPE html>
{% extends "CRUD/base.html" %}

{% block body_block %}

<h3>Album Form:</h3>
<form method="POST">
  {{ album_form.as_p }}
  {% csrf_token %}

  <input type="submit" name="submit" value="Add" class="btn btn-primary">

</form>
{% endblock %}

templates/CRUD/album_list.html
<!DOCTYPE html>
{% extends "CRUD/base.html" %}

{% block body_block %}
<h4 style="text-align:center;">Artist Name: <span style="font-weight:bold;">{{ musician_info.first_name }} {{ musician_info.last_name }}</span></h4>
<h4 style="text-align:center;">Instrument: <span style="font-weight:bold;">{{ musician_info.instrument }}</span></h4>
<h4 style="text-align:center;">Artist Rating: <span style="font-weight:bold;">{{ musician_rating_avg.num_stars__avg  }}</span></h4>

<div style="text-align:center;"><a href="{% url 'CRUD:update_musician' musician_id=musician_info.id %}" class="btn btn-success btn-sm">Update</a>
  <a href="{% url 'CRUD:delete_musician' musician_id=musician_info.id %}" onclick="return confirm('Delete Musician?')" class="btn btn-danger btn-sm">Delete</a> </div>


<h3>List of Albums:</h3>
<table class="table table-bordered">
  <tr>
    <th>Album Name</th>
    <th>Release Date</th>
    <th>Rating</th>
    <th>Action</th>
  </tr>
  {% for album in album_list %}
  <tr>
     <td>{{ album.name }}</td>
    <td>{{ album.release_date|date:"M d, Y" }}</td>
    <td>{{ album.num_stars }}</td>

    <td> <a href="{% url 'CRUD:update_album' album_id=album.id %}"><input type="submit" name="submit" value="Update" class="btn btn-success btn-sm"></a>
         <a href="{% url 'CRUD:delete_album' album_id=album.id %}" class="btn btn-danger btn-sm" onclick="return confirm('Delete This Album?')">Delete</a> </td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

templates/CRUD/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <title>{{ title }}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'CRUD:index' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'CRUD:musician_form' %}">Add Musician</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'CRUD:album_form' %}">Add Album</a>
    </li>
  </ul>
</nav>

<div class="container">
{% block body_block %}

{% endblock %}
</div>

  </body>
</html>

templates/CRUD/delete.html
{% extends 'CRUD/base.html' %}
{% block body_block %}
<div class="alert alert-danger">{{ delete_success }}</div>
{% endblock %}

templates/CRUD/index.html
<!DOCTYPE html>
{% extends "CRUD/base.html" %}

{% block body_block %}

<h3>List of Musicians:</h3>

<ol>
  {% if musician_list %}
  {% for musician in musician_list %}
  <li><a href="{% url 'CRUD:album_list' musician_id=musician.id %}">{{ musician.first_name }} {{ musician.last_name }}</a></li>

  {% endfor %}
  {% else %}
  <h4>No Musician in the list</h4>
  {% endif %}
</ol>

{% endblock %}

templates/CRUD/musician_form.html
<!DOCTYPE html>
{% extends "CRUD/base.html" %}
{% block body_block %}

<h3>Musician Form:</h3>
<form method="POST">
  {{ musician_form.as_p }}
  {% csrf_token %}

  <input type="submit" name="submit" value="Add" class="btn btn-primary">

</form>
{% endblock %}

templates/CRUD/update_album.html
{% extends 'CRUD/base.html' %}
{% block body_block %}
<h4>Update Album</h4>
{% if success_text %}
<div class='alert alert-success'>{{ success_text }}</div>
{% endif %}
<form method="POST">
  {{ update_form.as_p }}
  {% csrf_token %}
<input type="submit" name="submit" value="Update" class="btn btn-success btn-sm">
</form>
<br>

{% endblock %}

templates/CRUD/update_musician.html
{% extends 'CRUD/base.html' %}
{% block body_block %}
<h4>Edit Artist</h4>
<form method="POST">
  {{ update_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Update" class="btn btn-info btn-sm">
</form>
{% endblock %}